## Python for NLP: Word Embeddings for Deep Learning in Keras
https://stackabuse.com/python-for-nlp-word-embeddings-for-deep-learning-in-keras/

In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

/home/rodrigo/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/rodrigo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/rodrigo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/rodrigo/anaconda3/lib/python3.6/site-p

In [2]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]

In [3]:
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [4]:
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)

In [12]:
#  all_words

NameError: name 'vocab_length' is not defined

In [14]:
unique_words = set(all_words)
print(len(unique_words))
vocab_length = len(unique_words)

45


In [15]:
embedded_sentences = [one_hot(sent, vocab_length) for sent in corpus]
print(embedded_sentences)

[[42, 2, 6, 2, 43], [18, 12, 26, 19, 31, 37, 41], [20, 40, 20, 41, 2, 26], [41, 24], [20, 31, 19, 44, 31, 37, 41], [21, 37, 19, 37], [22, 21, 38, 37, 28, 43], [41, 2, 37, 15, 43], [2, 4], [15, 43, 28], [34, 39], [41, 26, 3, 7], [31, 1, 37, 37, 18, 43], [18, 43, 26, 2], [31, 18, 37, 16], [18, 4, 2, 34]]


In [16]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [17]:
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[42  2  6  2 43  0  0]
 [18 12 26 19 31 37 41]
 [20 40 20 41  2 26  0]
 [41 24  0  0  0  0  0]
 [20 31 19 44 31 37 41]
 [21 37 19 37  0  0  0]
 [22 21 38 37 28 43  0]
 [41  2 37 15 43  0  0]
 [ 2  4  0  0  0  0  0]
 [15 43 28  0  0  0  0]
 [34 39  0  0  0  0  0]
 [41 26  3  7  0  0  0]
 [31  1 37 37 18 43  0]
 [18 43 26  2  0  0  0]
 [31 18 37 16  0  0  0]
 [18  4  2 34  0  0  0]]


In [18]:
model = Sequential()
model.add(Embedding(vocab_length, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 20)             900       
_________________________________________________________________
flatten_1 (Flatten)          (None, 140)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 141       
Total params: 1,041
Trainable params: 1,041
Non-trainable params: 0
_________________________________________________________________
None


In [20]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)


Instructions for updating:
Use tf.cast instead.
Epoch 1/100
16/16 [==============================] - 1s 65ms/step - loss: 0.6902 - acc: 0.5625
Epoch 2/100
16/16 [==============================] - 0s 612us/step - loss: 0.6869 - acc: 0.6250
Epoch 3/100
16/16 [==============================] - 0s 360us/step - loss: 0.6840 - acc: 0.6250
Epoch 4/100
16/16 [==============================] - 0s 229us/step - loss: 0.6810 - acc: 0.6875
Epoch 5/100
16/16 [==============================] - 0s 162us/step - loss: 0.6776 - acc: 0.6875
Epoch 6/100
16/16 [==============================] - 0s 169us/step - loss: 0.6745 - acc: 0.6875
Epoch 7/100
16/16 [==============================] - 0s 122us/step - loss: 0.6711 - acc: 0.6875
Epoch 8/100
16/16 [==============================] - 0s 275us/step - loss: 0.6679 - acc: 0.7500
Epoch 9/100
16/16 [==============================] - 0s 136us/step - loss: 0.6646 - acc: 0.8125
Epoch 10/100
16/16 [==============================] - 0s 155us/step - loss: 0.6613 - acc:

Epoch 84/100
16/16 [==============================] - 0s 92us/step - loss: 0.3491 - acc: 0.9375
Epoch 85/100
16/16 [==============================] - 0s 96us/step - loss: 0.3448 - acc: 0.9375
Epoch 86/100
16/16 [==============================] - 0s 78us/step - loss: 0.3406 - acc: 0.9375
Epoch 87/100
16/16 [==============================] - 0s 99us/step - loss: 0.3364 - acc: 0.9375
Epoch 88/100
16/16 [==============================] - 0s 95us/step - loss: 0.3322 - acc: 0.9375
Epoch 89/100
16/16 [==============================] - 0s 112us/step - loss: 0.3281 - acc: 0.9375
Epoch 90/100
16/16 [==============================] - 0s 85us/step - loss: 0.3240 - acc: 0.9375
Epoch 91/100
16/16 [==============================] - 0s 97us/step - loss: 0.3199 - acc: 0.9375
Epoch 92/100
16/16 [==============================] - 0s 84us/step - loss: 0.3159 - acc: 0.9375
Epoch 93/100
16/16 [==============================] - 0s 85us/step - loss: 0.3119 - acc: 0.9375
Epoch 94/100
16/16 [===================

In [21]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 93.750000


### Loading Pretrained Word Embeddings

In [27]:
from numpy import array
from keras.preprocessing.text import one_hot, Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [28]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]

In [29]:
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [30]:
word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)

In [32]:
vocab_length = len(word_tokenizer.word_index) + 1

In [33]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)
print(embedded_sentences)

[[14, 3, 15, 16, 1], [4, 17, 6, 9, 5, 7, 2], [18, 19, 20, 2, 3, 21], [22, 23], [24, 25, 26, 27, 5, 7, 2], [28, 8, 9, 29], [30, 31, 32, 8, 33, 1], [2, 3, 8, 34, 1], [10, 11], [35, 36, 37], [12, 38], [2, 6, 39, 40], [5, 41, 13, 7, 4, 1], [4, 1, 6, 10], [5, 42, 13, 43], [4, 11, 3, 12]]


In [34]:
from nltk.tokenize import word_tokenize

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')

print(padded_sentences)

[[14  3 15 16  1  0  0]
 [ 4 17  6  9  5  7  2]
 [18 19 20  2  3 21  0]
 [22 23  0  0  0  0  0]
 [24 25 26 27  5  7  2]
 [28  8  9 29  0  0  0]
 [30 31 32  8 33  1  0]
 [ 2  3  8 34  1  0  0]
 [10 11  0  0  0  0  0]
 [35 36 37  0  0  0  0]
 [12 38  0  0  0  0  0]
 [ 2  6 39 40  0  0  0]
 [ 5 41 13  7  4  1  0]
 [ 4  1  6 10  0  0  0]
 [ 5 42 13 43  0  0  0]
 [ 4 11  3 12  0  0  0]]


Download glove.6B.100d.txt from https://www.kaggle.com/terenceliu4444/glove6b100dtxt/download

In [46]:
from numpy import array
from numpy import asarray
from numpy import zeros

embeddings_dictionary = dict()
glove_file = open('data/glove.6B.100d.txt', encoding="utf8")

In [47]:
for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32')
    embeddings_dictionary [word] = vector_dimensions

glove_file.close()

In [48]:
embedding_matrix = zeros((vocab_length, 100))
for word, index in word_tokenizer.word_index.items():
    embedding_vector = embeddings_dictionary.get(word)
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector

In [49]:
model = Sequential()
embedding_layer = Embedding(vocab_length, 100, weights=[embedding_matrix], input_length=length_long_sentence, trainable=False)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [50]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 7, 100)            4400      
_________________________________________________________________
flatten_4 (Flatten)          (None, 700)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 701       
Total params: 5,101
Trainable params: 701
Non-trainable params: 4,400
_________________________________________________________________
None


In [51]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)

Epoch 1/100
16/16 [==============================] - 0s 25ms/step - loss: 0.5466 - acc: 0.8125
Epoch 2/100
16/16 [==============================] - 0s 74us/step - loss: 0.5275 - acc: 0.8125
Epoch 3/100
16/16 [==============================] - 0s 102us/step - loss: 0.5118 - acc: 0.8125
Epoch 4/100
16/16 [==============================] - 0s 97us/step - loss: 0.4960 - acc: 0.8125
Epoch 5/100
16/16 [==============================] - 0s 117us/step - loss: 0.4804 - acc: 0.8750
Epoch 6/100
16/16 [==============================] - 0s 92us/step - loss: 0.4651 - acc: 0.9375
Epoch 7/100
16/16 [==============================] - 0s 199us/step - loss: 0.4502 - acc: 0.9375
Epoch 8/100
16/16 [==============================] - 0s 131us/step - loss: 0.4354 - acc: 1.0000
Epoch 9/100
16/16 [==============================] - 0s 200us/step - loss: 0.4211 - acc: 1.0000
Epoch 10/100
16/16 [==============================] - 0s 275us/step - loss: 0.4074 - acc: 1.0000
Epoch 11/100
16/16 [=======================

Epoch 86/100
16/16 [==============================] - 0s 113us/step - loss: 0.0686 - acc: 1.0000
Epoch 87/100
16/16 [==============================] - 0s 166us/step - loss: 0.0676 - acc: 1.0000
Epoch 88/100
16/16 [==============================] - 0s 138us/step - loss: 0.0666 - acc: 1.0000
Epoch 89/100
16/16 [==============================] - 0s 148us/step - loss: 0.0656 - acc: 1.0000
Epoch 90/100
16/16 [==============================] - 0s 347us/step - loss: 0.0647 - acc: 1.0000
Epoch 91/100
16/16 [==============================] - 0s 118us/step - loss: 0.0638 - acc: 1.0000
Epoch 92/100
16/16 [==============================] - 0s 146us/step - loss: 0.0629 - acc: 1.0000
Epoch 93/100
16/16 [==============================] - 0s 132us/step - loss: 0.0621 - acc: 1.0000
Epoch 94/100
16/16 [==============================] - 0s 108us/step - loss: 0.0612 - acc: 1.0000
Epoch 95/100
16/16 [==============================] - 0s 277us/step - loss: 0.0604 - acc: 1.0000
Epoch 96/100
16/16 [==========

In [52]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))


Accuracy: 100.000000


### Word Embeddings with Keras Functional API

In [53]:
from keras.models import Model
from keras.layers import Input

deep_inputs = Input(shape=(length_long_sentence,))
embedding = Embedding(vocab_length, 100, weights=[embedding_matrix], input_length=length_long_sentence, trainable=False)(deep_inputs) # line A
flatten = Flatten()(embedding)
hidden = Dense(1, activation='sigmoid')(flatten)
model = Model(inputs=deep_inputs, outputs=hidden)

In [54]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 7)                 0         
_________________________________________________________________
embedding_5 (Embedding)      (None, 7, 100)            4400      
_________________________________________________________________
flatten_5 (Flatten)          (None, 700)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 701       
Total params: 5,101
Trainable params: 701
Non-trainable params: 4,400
_________________________________________________________________
None


In [55]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)

print('Accuracy: %f' % (accuracy*100))

Epoch 1/100
16/16 [==============================] - 1s 35ms/step - loss: 0.7698 - acc: 0.4375
Epoch 2/100
16/16 [==============================] - 0s 71us/step - loss: 0.7489 - acc: 0.4375
Epoch 3/100
16/16 [==============================] - 0s 141us/step - loss: 0.7256 - acc: 0.4375
Epoch 4/100
16/16 [==============================] - 0s 97us/step - loss: 0.6993 - acc: 0.4375
Epoch 5/100
16/16 [==============================] - 0s 336us/step - loss: 0.6757 - acc: 0.5625
Epoch 6/100
16/16 [==============================] - 0s 107us/step - loss: 0.6524 - acc: 0.6250
Epoch 7/100
16/16 [==============================] - 0s 160us/step - loss: 0.6299 - acc: 0.6250
Epoch 8/100
16/16 [==============================] - 0s 105us/step - loss: 0.6081 - acc: 0.6875
Epoch 9/100
16/16 [==============================] - 0s 134us/step - loss: 0.5870 - acc: 0.6875
Epoch 10/100
16/16 [==============================] - 0s 428us/step - loss: 0.5668 - acc: 0.7500
Epoch 11/100
16/16 [======================

Epoch 86/100
16/16 [==============================] - 0s 186us/step - loss: 0.0907 - acc: 1.0000
Epoch 87/100
16/16 [==============================] - 0s 104us/step - loss: 0.0893 - acc: 1.0000
Epoch 88/100
16/16 [==============================] - 0s 104us/step - loss: 0.0880 - acc: 1.0000
Epoch 89/100
16/16 [==============================] - 0s 100us/step - loss: 0.0868 - acc: 1.0000
Epoch 90/100
16/16 [==============================] - 0s 123us/step - loss: 0.0855 - acc: 1.0000
Epoch 91/100
16/16 [==============================] - 0s 104us/step - loss: 0.0843 - acc: 1.0000
Epoch 92/100
16/16 [==============================] - 0s 156us/step - loss: 0.0831 - acc: 1.0000
Epoch 93/100
16/16 [==============================] - 0s 266us/step - loss: 0.0820 - acc: 1.0000
Epoch 94/100
16/16 [==============================] - 0s 158us/step - loss: 0.0808 - acc: 1.0000
Epoch 95/100
16/16 [==============================] - 0s 106us/step - loss: 0.0797 - acc: 1.0000
Epoch 96/100
16/16 [==========